# Subject independance check

libraries

In [1]:
import pandas as pd

datasets

In [3]:
htad = pd.read_csv("../datasets/HTAD.csv")
har70 = pd.read_csv("../datasets/HAR70+.csv")
mhad = pd.read_csv("../datasets/berkeley.csv")

In [7]:
htad.head()

,userid,label,v1_mfcc1,v1_mfcc2,v1_mfcc3,v1_mfcc4,v1_mfcc5,v1_mfcc6,v1_mfcc7,v1_mfcc8,...,v2_maxX,v2_maxY,v2_maxZ,v2_corXY,v2_corXZ,v2_corYZ,v2_meanMagnitude,v2_sdMagnitude,v2_auc,v2_meanDif
0,user1,watch_tv,120.078886,3.025171,0.390508,-1.777848,-9.216060,-6.567632,-9.918761,-9.145534,...,0.097412,1.088135,0.227051,0.900163,-0.729511,-0.863478,1.014805,0.060424,70.021543,-0.000364
1,user1,watch_tv,130.243139,2.552278,-6.457879,-7.440159,-3.070106,-3.475476,-5.718819,-2.878174,...,0.703613,1.424805,0.818115,-0.210431,0.319599,-0.722541,1.005713,0.162644,79.451303,-0.006234
2,user1,watch_tv,122.259209,1.970267,-8.980575,-10.222030,-3.564994,-2.496906,-5.584900,-6.730588,...,0.312500,0.972656,-0.070312,-0.018862,-0.093852,-0.305722,1.002809,0.006100,77.216317,0.000019
3,user1,watch_tv,122.609566,3.188740,-7.049397,-10.569875,-0.220824,-0.649459,-4.975825,-6.856288,...,0.349854,1.020020,-0.053223,0.492439,0.273064,-0.023051,1.002878,0.021292,75.215866,-0.000023
4,user1,watch_tv,121.393023,1.338798,-8.706183,-8.654997,-4.935310,-3.401656,-5.031361,-7.957924,...,0.322266,0.955078,-0.076904,-0.226296,-0.217439,-0.053895,1.003427,0.002849,71.243346,-0.000083

## HTAD check

In [11]:
htad.groupby(["userid", "label"])["label"].value_counts()

userid  label
user1   brush_teeth          59
        eat_chips           153
        mop_floor            56
        sweep                47
        type_on_keyboard     49
        wash_hands           36
        watch_tv             66
user2   brush_teeth          57
        eat_chips            65
        mop_floor            63
        sweep                68
        type_on_keyboard     63
        wash_hands           79
        watch_tv             71
user3   brush_teeth          64
        eat_chips            64
        mop_floor            62
        sweep                63
        type_on_keyboard     67
        wash_hands           65
        watch_tv             69
Name: count, dtype: int64

In [12]:
htad["userid"].value_counts()

userid
user1    466
user2    466
user3    454
Name: count, dtype: int64

## HAR70+ Check

In [13]:
har70.head()

,userid,label,v1_meanX,v1_meanY,v1_meanZ,v1_sdX,v1_sdY,v1_sdZ,v1_maxX,v1_maxY,...,v2_minX2,v2_minY2,v2_minZ2,v2_corXY2,v2_corXZ2,v2_corYZ2,v2_meanMagnitude2,v2_sdMagnitude2,v2_auc2,v2_meanDif2
0,501,walking,-0.982145,-0.021472,-0.218573,0.063841,0.110760,0.061010,-0.836035,0.180957,...,-1.147290,-0.435913,-0.679614,0.249326,-0.571290,-0.128164,1.005442,0.070684,150.816332,-0.010199
1,501,walking,-1.003945,-0.055020,-0.150732,0.114290,0.075176,0.083377,-0.817676,0.066455,...,-1.346973,-0.321582,-0.670654,0.542167,-0.378275,-0.520994,1.038137,0.168264,155.720618,0.120175
2,501,walking,-0.994657,-0.041391,-0.161117,0.067852,0.107584,0.137541,-0.888013,0.177832,...,-1.148071,-0.241113,-0.689697,0.012539,-0.447214,-0.424962,1.002341,0.073532,150.351206,-0.222950
3,501,walking,-1.005066,-0.086511,-0.170156,0.105186,0.082683,0.085037,-0.859424,0.073731,...,-1.314575,-0.278320,-0.684375,0.127624,-0.448272,-0.365001,1.038057,0.152563,155.708485,-0.262919
4,501,walking,-0.999507,-0.084847,-0.207869,0.091950,0.081913,0.078310,-0.856299,0.057519,...,-1.287256,-0.268579,-0.648730,0.185175,-0.464170,-0.494353,1.007433,0.124515,151.114953,0.433201

In [19]:
len(har70["userid"].unique())

18

In [ ]:
har70.groupby(["userid", "label"])["label"]

# MHAD check

In [20]:
mhad.head()

,class,v1_Mic01mfcc1,v1_Mic01mfcc2,v1_Mic01mfcc3,v1_Mic01mfcc4,v1_Mic01mfcc5,v1_Mic01mfcc6,v1_Mic01mfcc7,v1_Mic01mfcc8,v1_Mic01mfcc9,...,v3_minDist21,v3_minDist22,v3_minDist23,v3_minDist24,v3_minDist25,v3_minDist26,v3_minDist27,v3_minDist28,v3_minDist29,v3_minDist30
0,a01,0.079710,0.769658,0.830407,0.356513,0.782229,0.190463,0.861372,0.567263,0.603267,...,0.249865,0.285205,0.487818,0.228206,0.097392,0.286039,0.441920,0.326167,0.202072,0.194989
1,a01,0.159042,0.703198,0.654148,0.532655,0.715287,0.218365,0.857341,0.585356,0.754775,...,0.204976,0.323691,0.563936,0.244460,0.093437,0.234497,0.413829,0.196275,0.366608,0.229414
2,a01,0.201678,0.668549,0.560725,0.448048,0.766439,0.251589,0.716053,0.686217,0.698206,...,0.201847,0.327419,0.602608,0.208358,0.080864,0.241457,0.387119,0.195520,0.280076,0.128845
3,a01,0.126777,0.784201,0.730486,0.336550,0.733965,0.157373,0.981363,0.620040,0.561619,...,0.127575,0.230398,0.453026,0.138018,0.082161,0.132621,0.343044,0.150898,0.355903,0.000000
4,a01,0.097669,0.758022,0.820271,0.322435,0.751854,0.235266,0.830231,0.591475,0.505623,...,0.250149,0.232952,0.472293,0.209424,0.072610,0.190090,0.392121,0.229628,0.396794,0.194958